- name: Redis | Install Redis PPA
  apt_repository: repo='ppa:chris-lea/redis-server' update_cache=yes

- name: Redis | Install Redis
  apt: pkg=redis-server state=latest force=yes

- name: Redis | Enable with systemd
  systemd:
    name: redis-server
    enabled: yes
    state: started
