---

- hosts: all
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - base
    - python
    - postgres
    - redis
    - node

  vars_files:
    - vagrant.yml
    - env_vars/base.yml
