---

- hosts: all
  become: yes # This means that all tasks will be executed with sudo
  roles:
    - base
    - python
    - virtualenv
    - node
    - postgres
    - redis
    # - celery

  vars_files:
    - vagrant.yml
    - env_vars/base.yml
