---
- name: Add key for jonathonf PPA
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    state: present

- name: Add jonathonf PPA
  apt_repository:
    repo: deb http://ppa.launchpad.net/jonathonf/python-3.7/ubuntu xenial main
    state: present

- name: Install Python 3.7
  apt:
    name: python3.7
    state: present
    update_cache: yes

- name: Upgrade pip
  pip: name=pip state=latest

- name: update .bash_aliases
  become_user: vagrant
  lineinfile:
    dest: /home/vagrant/.bash_aliases
    line: 'alias p3="python3.7"'
    mode: 0644
    state: present
    create: yes
