---
- name: Install pip
  apt:
    name : "python3-pip"
    state: present

- name: upgrade pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- name: Set up global requirements
  pip:
    requirements: /vagrant/ansible_requirements.txt

- name: set up aliases
  become_user: vagrant
  blockinfile:
    dest: "{{ home_directory }}/.bash_aliases"
    insertafter: EOF
    state: present
    create: yes
    block: |
      # Shortcuts for the project
      alias activate="cd $HOME/app; workon {{ project_name }}"
      alias runserver="activate; python manage.py runserver 0.0.0.0:8000"
      alias shell="activate; python manage.py shell"

- name: setup pyenv variables
  become_user: vagrant
  blockinfile:
    path: "{{ home_directory }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK PYENV"
    insertafter: EOF
    state: present
    block: |
      export PATH="/home/vagrant/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  tags:
    - debug

- name: install pyenv prerequisities
  apt:
    name : ['make', 'build-essential', 'libssl-dev', 'zlib1g-dev', 'libbz2-dev', 'libreadline-dev', 'libsqlite3-dev', 'wget', 'curl', 'llvm', 'libncurses5-dev', 'libncursesw5-dev', 'xz-utils', 'tk-dev', 'libffi-dev', 'liblzma-dev', 'python-openssl', 'git']
    state: present

- name: install pyenv
  become_user: vagrant
  shell: curl https://pyenv.run | bash
  tags:
    - debug

- name: install poetry
  become_user: vagrant
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
  tags:
    - debug
