---
- name: Install pip
  apt:
    name : "{{ python_version }}-pip"
    state: present

- name: upgrade pip
  pip:
    name: pip
    executable: "{{ pip_version }}"
    extra_args: --upgrade

- name: remove apt pip
  apt:
    name: "{{ python_version }}-pip"
    state: absent

- name: Set up global requirements
  pip:
    requirements: /vagrant/ansible_requirements.txt
    executable: "{{ pip_version }}"

- name: set up aliases
  become_user: vagrant
  blockinfile:
    dest: "{{ home_directory }}/.bash_aliases"
    insertafter: EOF
    state: present
    create: yes
    block: |
      # Shortcuts for the project
      alias activate="cd $HOME/app; workon {{ project_name }}"
      alias runserver="activate; python manage.py runserver 0.0.0.0:8000"
      alias shell="activate; python manage.py shell"

- name: setup pyenv variables
  become_user: vagrant
  blockinfile:
    path: "{{ home_directory }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK PYENV"
    insertafter: EOF
    state: present
    block: |
      export PATH="/home/vagrant/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  tags:
    - debug

- name: install pyenv
  become_user: vagrant
  shell: curl https://pyenv.run | bash
  tags:
    - debug
