---
- name: Install pip
  apt:
    name : "{{ python_version }}-pip"
    state: present

# - name: Add key for jonathonf PPA
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
#     state: present

# - name: Add jonathonf PPA
#   apt_repository:
#     repo: deb http://ppa.launchpad.net/jonathonf/python-3.7/ubuntu xenial main
#     state: present

# - name: Install Python 3.7
#   apt:
#     name: python3.7
#     state: present
#     update_cache: yes

# - name: update .bash_aliases
#   become_user: vagrant
#   lineinfile:
#     dest: "{{ home_directory }}/.bash_aliases"
#     line: 'alias p3="python3.7"'
#     mode: 0644
#     state: present
#     create: yes

- name: upgrade pip
  pip:
    name: pip
    executable: "{{ pip_version }}"
    extra_args: --upgrade

- name: remove apt pip
  apt:
    name: "{{ python_version }}-pip"
    state: absent

- name: Set up global requirements
  pip:
    requirements: /vagrant/ansible_requirements.txt
    executable: "{{ pip_version }}"

- name: Set up venv, install python packages
  become_user: vagrant
  pip:
    name: cookiecutter
    virtualenv: "{{ home_directory }}/.virtualenvs/{{ project_name }}"

- name: Install virtualenvwrapper
  become_user: vagrant
  pip:
    name: virtualenvwrapper
    extra_args: --user
    executable: "{{ pip_version }}"

- name: Update .bashrc for virtualenvwrapper
  blockinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: EOF
    state: present
    block: |
      # Virtualenvwrapper
      export "VIRTUALENVWRAPPER_PYTHON=/usr/bin/{{ python_version }}"
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/Devel
      source "{{ home_directory }}/.local/bin/virtualenvwrapper.sh"

- name: Make a virtualenv
  shell: "{{ wrapper_bin }} && mkvirtualenv {{ project_name }}"
  args:
    executable: /bin/bash
    creates: "{{ virtualenv_dir}}/{{ project_name }}"
  environment:
    path: /usr/local/bin:/usr/bin:/bin
