---
- name: Create / remove a local node_modules directory
  become_user: vagrant
  file:
    path: "{{ home_directory }}/node_modules_app"
    state: 'directory'

- name: Mount / unmount node_modules
  mount:
    path: "{{ home_directory }}/app/node_modules"
    src: "{{ home_directory }}/node_modules_app"
    state: 'mounted'
    fstype: none
    opts: bind
    boot: yes
  become: yes
  become_user: root

# Taken from https://gist.github.com/komuw/b3b5d24977d4df7bd549
- name: Install nvm
  become_user: vagrant
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | sh
    creates={{ home_directory }}/.nvm/nvm.sh

- name: Install Node.js
  become_user: vagrant
  shell: '. {{ home_directory }}/.nvm/nvm.sh && nvm install node'
  args:
    creates: "{{ home_directory }}/.nvm/versions/node"
    chdir: "{{ home_directory }}"
    executable: /bin/bash
