---
# Taken from https://gist.github.com/komuw/b3b5d24977d4df7bd549
- name: Install nvm
  become_user: vagrant
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | sh
    creates={{ home_directory }}/.nvm/nvm.sh

- name: Install Node.js
  become_user: vagrant
  shell: '. {{ home_directory }}/.nvm/nvm.sh && nvm install node'
  args:
    creates: "{{ home_directory }}/.nvm/versions/node"
    chdir: "{{ home_directory }}"
    executable: /bin/bash

- name: Copy package.json to app
  become_user: vagrant
  template:
    src: package.j2
    dest: "{{ home_directory }}/app/package.json"
    owner: vagrant
    group: vagrant


# These don't work because of
#
# - name: Install gulp globally
#   become: yes
#   npm:
#     name: gulp
#     path: "{{ home_directory }}/app"
#     executable: "{{ home_directory }}/.nvm/versions/node/v11.6.0/bin/npm"
#     global: yes

# - name: Install packages from package.json
#   # become_user: vagrant
#   npm:
#     path: "{{ home_directory }}/app"
#     executable: "{{ home_directory }}/.nvm/versions/node/v11.6.0/bin/npm"
#     state: present
