- name: Update apt
  apt: update_cache=yes

- name: install base packages
  apt:
    name : ['locales', 'build-essential', 'acl', 'ntp', 'htop', 'git', 'tcl', 'zlib1g-dev', 'libbz2-dev', 'libreadline-dev', 'python-openssl', 'libssl-dev', 'libsqlite3-dev', 'libffi-dev']
    state: present

- name: set timezone to Europe/Stockholm
  timezone:
    name: Europe/Stockholm
